# Generated by Django 5.1.1 on 2025-01-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_functionalrequirement_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='functionalrequirement',
            name='feature_description',
        ),
        migrations.RemoveField(
            model_name='functionalrequirement',
            name='feature_name',
        ),
        migrations.AddField(
            model_name='functionalrequirement',
            name='features',
            field=models.ManyToManyField(related_name='functional_requirements', to='api.features'),
        ),
    ]
