# Generated by Django 5.1.1 on 2025-02-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
    ]
